### ISSUE TITLE
Game quality setting not applied

### ISSUE THREAD

**Issue by RenaudDelcoigne** [thecodingmachine/workadventure#1096]
Since several weeks, the game quality setting stopped being applied revealing performance issues.

When changing to 40 or 20fps modes, it still runs at 60fps, using a lot of cpu power, my laptop is louder and hotter, and my system is slower.

It's really downgrading the user experience, since WorkAdventure is an app mainly made for home working, running in background constantly, but if the performances of the computer are downgraded using it, it's counterproductive and a big issue.

This issue has been encountered with the most recent public versions of Google Chrome and Firefox on Windows 10.

**Comment by moufmouf** [comment]
Hi Renaud!

Thanks for the issue, we'll check it out.
On the bright side, we are about to release a new version that will slash down power consumption by a tremendous amount.
Just 2 weeks more and things should be **a lot** smoother.

**Comment by mint-jar** [comment]
Hi @moufmouf,

Do you have an ETA on this update or a version number where this will be included? I would love to use workadventure again at work :smile:

**Comment by mint-jar** [comment]
Never mind. Has been fixed. 

:heart: the improvements guys!

**Comment by RenaudDelcoigne** [comment]
The new version is really great, performances are a lot better, and it looks better too !

The game quality setting is still not applied yet but I don't think it is relevant anymore.

**Comment by mint-jar** [comment]
@RenaudDelcoigne for me the settings are applied (I needed to change settings as they where to minimal now :sweat_smile:).

**Comment by RenaudDelcoigne** [comment]
When changing the game quality settings, it reboots the webapp but I see no difference in framerate between any of the settings, 20fps should be stuttery compared to 60fps.
